# Generated by Django 2.2.7 on 2019-12-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsystemAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '校区表 Branch'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级表 Classlist'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程表 Course'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name_plural': '上课记录表 CourseRecord'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name_plural': '客户跟进表 CustomerFollowUp'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': '客户表 Customers'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': '学生报名表 Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': '缴费记录表 Payment'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表 Role'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name_plural': '学习记录表 StudyRecord'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': '标签表 Tags'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户表 UserProfile'},
        ),
    ]
