# Generated by Django 2.2.7 on 2019-12-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsystemAPP', '0002_auto_20191204_2153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('student', 'course_record')},
        ),
    ]
