# Generated by Django 2.2.7 on 2019-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsystemAPP', '0004_auto_20191205_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '转介绍'), (1, 'Google'), (2, 'Facebook'), (3, 'Twitter'), (4, '其他互联网'), (5, '机构合作')], default=1),
        ),
    ]
