# Generated by Django 2.2.7 on 2019-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsystemAPP', '0005_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已报名'), (1, '未报名'), (2, '有意向'), (3, '考虑中'), (4, '不学了')], default=1),
        ),
    ]
